CREATE DATABASE wildlife_track;

\c wildlife_track;

CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE endangered(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    type VARCHAR,
    health VARCHAR,
    age VARCHAR
);

CREATE TABLE sightings(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR,
    name VARCHAR,
    animalid INTEGER
);


CREATE DATABASE wildlife_track_test WITH TEMPLATE wildlife_track;

