
CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;

CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    animaltype VARCHAR,
    health VARCHAR,
    age VARCHAR
);


CREATE TABLE sightings (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR,
    name VARCHAR,
    animalid INTEGER
);


CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;

